In [22]:
import numpy as np
try:
    n = int(input("Enter n: "))
    diag = np.arange(1,n+1,1)
    print(np.diag(diag))
except:
    print("Error")

Enter n: 5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [31]:
n = int(input("Enter n: "))
arr = np.zeros((n,n), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

Enter n: 6
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [40]:
n,m,r,c = input().split()
arr = np.ones((int(n), int(m)), dtype=int)
arr[::int(r),::]=0
arr[::,::int(c)]=0
print(arr)

6 7 2 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [46]:
n, m = input().split()
arr = np.zeros((int(m), int(n)), dtype=int)
arr[0] = np.arange(int(n))
print(arr)

3 4
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [53]:
arr = np.array(input().split(), dtype=int)
arr[arr!=0]=-1
arr

1 2 3 0 4 5 6 0 7 8 9 0


array([-1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1,  0])

In [63]:
arr = np.array(input().split(), dtype=int)
print("Number of zeros: ", len(arr[arr==0]))
print("Number of non-zeros: ", len(arr[arr!=0]))

1 2 3 4 0 0
Number of zeros:  2
Number of non-zeros:  4


In [67]:
n = int(input("Enter n: "))
arr = np.ones((n+2, n+2), dtype=int)
arr[::, ::n+1]=0
arr[::n+1, ::] = 0
arr

Enter n: 4


array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [75]:
n = int(input("Enter n: "))
np.around(np.linspace(0, 1, n+2, dtype=float),3)[1:-1:]

Enter n: 10


array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

In [88]:
n = int(input("Enter n: "))
arr = np.around(np.random.random(n),3)
print("initial vector: ",arr)
arr[arr == np.max(arr)] = 0
print("Modified vector: ", arr)

Enter n: 5
initial vector:  [0.835 0.596 0.189 0.634 0.64 ]
Modified vector:  [-0.835  0.596  0.189  0.634  0.64 ]


In [90]:
n, m = input("Enter n, m: ").split()
arr = np.random.randint(0, int(m),(int(n),int(n)))
print("initial matrix:\n ",arr)
arr[arr == np.max(arr)] = np.max(arr)*-1
print("Modified matrix\n: ", arr)

Enter n, m: 5 10
initial vector:
  [[3 1 1 2 0]
 [5 9 3 5 7]
 [6 8 7 0 7]
 [2 8 6 2 5]
 [4 8 8 3 6]]
Modified vector
:  [[ 3  1  1  2  0]
 [ 5 -9  3  5  7]
 [ 6  8  7  0  7]
 [ 2  8  6  2  5]
 [ 4  8  8  3  6]]


In [123]:
A = np.array([[4,1,0,-1],[1,-3,4,0],[0,3,-2,4],[1,0,2,4]], dtype=int)
B = np.array([-9,7,12,12], dtype=int)

det = np.linalg.det(A)
temp_A = A.copy()
temp_A[:, 0] =  B
det_1 = np.linalg.det(temp_A)
temp_A = A.copy()
temp_A[:,1] = B
det_2 = np.linalg.det(temp_A)
temp_A = A.copy()
temp_A[:,2] = B
det_3 = np.linalg.det(temp_A)
temp_A = A.copy()
temp_A[:,3] = B
det_4 = np.linalg.det(temp_A)
X = np.array([round(det_1/det),round(det_2/det),round(det_3/det),round(det_4/det)])
print(A.dot(X))
print(np.round(np.linalg.solve(A, B),3))
X
print("No solutions, because determinant equals ", round(det))

[ 34  92 -72  20]
[-1.49028206e+16  4.47084618e+16  3.72570515e+16 -1.49028206e+16]
No solutions, because determinant equals  0


In [125]:
A = np.array([[4,2,1],[3,-2,0],[0,1,2]], dtype=int)
B = np.array([[2,0,2],[5,-7,-2],[1,0,-1]], dtype=int)
3*(A**2 - B**2) - 2*A*B

array([[  20,   12,  -13],
       [ -78, -163,  -12],
       [  -3,    3,   13]])

In [127]:
#task_4
coef_matrix = np.array([[5,3,-1],
                       [-2,0,4],
                       [3,5,-1]])
b_matrix = np.array([1,4,16])
inverse_matrix = np.linalg.inv(coef_matrix)
x_matrix = inverse_matrix.dot(b_matrix)
print("X array: ",x_matrix)
print("X array using linalg: ", np.linalg.solve(coef_matrix,b_matrix))
print("Checking rightness using multiplication: ", coef_matrix.dot(x_matrix))

X array:  [-2.73333333  4.76666667 -0.36666667]
X array using linalg:  [-2.73333333  4.76666667 -0.36666667]
Checking rightness using multiplication:  [ 1.  4. 16.]
